name: 'ArtifactedDockerImages'
description: 'Load Docker Images From Artifacts'
inputs:
  artifacts:
    description: 'list of artifact to download'
    required: false
runs:
  using: 'node16'
  main: 'dist/main.js'
