name: Share data between jobs

on: [push]

jobs:
  job_1:
    name: Add 3 and 7
    runs-on: ubuntu-latest
    steps:
      - shell: bash
        run: |
          expr 3 + 7 > math-homework.txt
      - name: Upload math result for job 1
        uses: actions/upload-artifact@v3
        with:
          name: homework
          path: math-homework.txt

  job_2:
    name: Multiply by 9
    needs: job_1
    runs-on: windows-latest
    steps:
      - name: Download math result for job 1
        uses: actions/download-artifact@v3
        with:
          name: homework
      - shell: bash
        run: |
          if [ -e math-homework.txt ]; then
            echo file exists
          else
            echo file do not exist
          fi

  job_3:
    name: downlod programatically
    needs: job_1
    runs-on: windows-latest
    steps:
      -
        id: Checkout
        uses: actions/checkout@v3
      -
        name: node setup
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: yarn
          cache-dependency-path: src/main/node/yarn.lock
      - name: yarn install
        run: yarn --cwd src/main/node/ install 
      - name: yarn build
        run: yarn --cwd src/main/node/ build
      - name: check artifacts
        run: node src/main/node/dist/main.js 

