# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:
    branches:
      - main
      - TestDockerMetadata
    tags:
      - 'v*'
  pull_request:
    branches: [ main ]
env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Get version from package.json
      run: echo MODULE_VERSION=v$(cat package.json | jq .version | sed -e 's/"//g') >> $GITHUB_OUTPUT

    - name: Extract Metadata for docker
      id: docker-meta
      uses: docker/metadata-action@v4.6.0
      with:
        images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
        tags: |
          type=ref,event=branch
          type=ref,event=pr
          type=semver,pattern={{version}},value=$MODULE_VERSION
          type=semver,pattern={{major}}.{{minor}},value=$MODULE_VERSION
          type=semver,pattern={{major}},value=$MODULE_VERSION

