# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:
    branches:
      - main
      - TestDockerMetadata
    tags:
      - 'v*'
  pull_request:
    branches: [ main ]
env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3.5.3

    - name: Get version from package.json
      id: version-number
      run: echo MODULE_VERSION=v$(cat package.json | jq .version | sed -e 's/"//g') >> $GITHUB_OUTPUT
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to the Container registry
      uses: docker/login-action@v2
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Extract Metadata for docker
      id: docker-meta
      uses: docker/metadata-action@v4.6.0
      env:
        MODULE_VERSION: ${{steps.version-number.outputs.MODULE_VERSION}}
      with:
        images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
        tags: |
          type=ref,event=branch
          type=ref,event=pr
          type=semver,pattern={{version}}
          type=semver,pattern={{major}}
          type=semver,pattern={{major}}.{{minor}}
          # type=semver,pattern={{version}},value=${{steps.version-number.outputs.MODULE_VERSION}}
          # type=semver,pattern={{major}}.{{minor}},value=${{steps.version-number.outputs.MODULE_VERSION}}
          # type=semver,pattern={{major}},value=${{steps.version-number.outputs.MODULE_VERSION}}

    - name: Build YJS image
      uses: docker/build-push-action@v3
      with:
        platforms: linux/amd64
        push: true
        tags: ${{ steps.docker-meta.outputs.tags }}
        labels: ${{ steps.docker-meta.outputs.labels }}

