# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest
    
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_PASSWORD: user
          POSTGRES_USER: 1234
          POSTGRES_DB: test  
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432
    steps:
    - uses: actions/checkout@v2
    - name: Cache local Maven repository
      uses: actions/cache@v2
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-
    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 11
    - name: prepare repository
      shell: bash
      env:
        GIT_USER: ${{ secrets.GIT_USER }}
        GIT_TOKEN: ${{ secrets.GIT_TOKEN }}
        BRANCH_NAME: ${{ github.head_ref }}
        PR_NUMBER: $${{ github.event.number}}
      run: |
        echo "MAVEN_OPTS='-Xms800m -Xmx800m'" > ~/.mavenrc
        echo -e "machine github.com\n  login $GIT_USER\n  password $GIT_TOKEN" >> ~/.netrc
        echo RunNumber: : ${GITHUB_RUN_NUMBER}
        echo Ref: ${GITHUB_REF}
        echo BRANCH_NAME: ${BRANCH_NAME}
        echo PR_NUMBER: ${PR_NUMBER}
        echo "${{ toJson(github) }}"
        # git submodule update --init --recursive
        # perl -pi -e 's/(wegas.build.number)=/$1=${GITHUB_RUN_NUMBER}/;s/(wegas.build.branch)=/$1=${BRANCH_NAME}/;s/(wegas.build.pr_branch)=/$1=$ENV{"TRAVIS_PULL_REQUEST_BRANCH"}/;s/(wegas.build.pr_number)=/$1=${PR_NUMBER}/;' wegas-core/src/main/resources/wegas.properties

    - name: Build with Maven
      run: mvn -B package --file pom.xml
