# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: CI test cache

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Cache local Maven repository
      uses: actions/cache@v2
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-
    - name: Setup Node
      uses: actions/setup-node@v1
      with:
        node-version: '11.10.1'
    - name: Get yarn cache directory path
      id: yarn-cache-dir-path
      run: echo YARN_CACHE_DIR=$(yarn cache dir) >> $GITHUB_ENV
    - uses: actions/cache@v2
      id: yarn-cache # use this to check for `cache-hit` (`steps.yarn-cache.outputs.cache-hit != 'true'`)
      with:
        path: ${YARN_CACHE_DIR}
        key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
        restore-keys: |
          ${{ runner.os }}-yarn-

    - name: Yarn install
      run: yarn install
    - name: List 
      shell: bash
      run: |
        echo YARN CACHE ${YARN_CACHE_DIR}
        ls -l ${YARN_CACHE_DIR}
        echo ".cache"
        ls -l ~/.cache
