
on:
  issues:
    types: [labeled]
jobs:
  Move_Labeled_Issue_On_Project_Board:
    runs-on: ubuntu-latest
    steps:
    - uses: konradpabjan/move-labeled-or-milestoned-issue@v2.0
      with:
        action-token: "${{ secrets.GH_ISSUE_TRIAGE }}"
        project-url: "https://github.com/maxencelaurent/GhActions/projects/1"
        column-name: "To do"
        label-name: "Project X"
        columns-to-ignore: "In progress,Done"
